[package]
name = "birddiskc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "birddisk"
path = "src/main.rs"

[dependencies]
birddisk_core = { path = "../birddisk_core" }
birddisk_vm = { path = "../birddisk_vm" }
birddisk_wasm = { path = "../birddisk_wasm" }
serde_json = "1"
